install:
  sudo cp micro-x.service /lib/systemd/system/
  sudo systemctl daemon-reload

start:
  sudo systemctl start micro-x.service

enable:
  sudo systemctl enable micro-x.service

stop:
  sudo systemctl stop micro-x.service

disable:
  sudo systemctl disable micro-x.service
  
